//! PowerShell profile path utilities and kuku config directory management.

use std::path::PathBuf;

/// Returns ~/.config/kuku/
pub fn config_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("kuku")
}

/// Returns ~/.config/kuku/assistant.toml
pub fn assistant_toml_path() -> PathBuf {
    config_dir().join("assistant.toml")
}

/// Returns ~/.config/kuku/kuku.toml
pub fn config_toml_path() -> PathBuf {
    config_dir().join("kuku.toml")
}

/// Returns the PowerShell profile path.
/// On Windows: ~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
/// Fallback: $PROFILE env var
pub fn powershell_profile_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("PROFILE") {
        return Some(PathBuf::from(p));
    }
    let docs = dirs::document_dir()?;
    Some(docs.join("PowerShell").join("Microsoft.PowerShell_profile.ps1"))
}

/// The marker comment used to identify kuku-managed lines in the profile.
pub const PROFILE_MARKER: &str = "# kuku managed block";
pub const PROFILE_MARKER_END: &str = "# kuku managed block end";

/// Generate the PowerShell block to inject into $PROFILE.
pub fn profile_block(kuku_exe: &str) -> String {
    format!(
        r#"{PROFILE_MARKER}
# Auto-generated by kuku init - do not edit manually

# Track exit codes via PSReadLine handler (non-invasive, no Prompt override)
Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {{
    $global:KukuLastExitCode = $LASTEXITCODE
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}}

Register-EngineEvent PowerShell.OnIdle -Action {{
    $code = $global:KukuLastExitCode
    $global:KukuLastExitCode = $null
    if ($code -and $code -ne 0) {{
        $lastCmd = (Get-History -Count 1).CommandLine
        if ($lastCmd) {{
            & "{kuku_exe}" assist --exit-code $code --command "$lastCmd" 2>$null
        }}
    }}
}} | Out-Null

# Ctrl+Shift+E: apply last kuku suggestion
Set-PSReadLineKeyHandler -Chord 'Ctrl+Shift+e' -ScriptBlock {{
    $suggestion = Get-Content "$env:TEMP\kuku_last_suggestion.txt" -ErrorAction SilentlyContinue
    if ($suggestion) {{
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($suggestion)
    }}
}}
{PROFILE_MARKER_END}
"#
    )
}
